### ISSUE TITLE
One More Field Needed for XSendFile

### ISSUE THREAD

**Issue by iYUYUE** [Instagit/owncloud-videojs#1]
According to this doc, XSendFilePath should be set for Ubuntu 12.10 or later. In my Ubuntu 15.04, the server will return 404 if it isn't set!
https://doc.owncloud.org/server/7.0/admin_manual/configuration/serving_static_files_configuration.html

**Comment by Instagit** [comment]
I specifically left that out, because I didn't need it on 14.04, but I'll add it then. Thanks!
