### ISSUE TITLE
Fast forward/seek not working

### ISSUE THREAD

**Issue by szewczyk-it** [Instagit/owncloud-videojs#3]
Video scrolling not working on Windows on browsers: Chrome, Firefox, Opera. Just works on MS Edge (OMG!). I tested it on Windows 8 and Windows 10 and nevest ownCloud (8.1.3-13.1)  in "VideoJS Sublime" app.
Bellow is link to effect on my computer:
https://youtu.be/3w8J9Q-Tp-s

**Comment by Instagit** [comment]
Thank you for the detailled report, I'm going to look into this.

1. What kind of video file are you having problems with (file extension, codecs)? 
2. What's the server configuration (OS version, webserver)?

I just tested with Firefox on Windows 7 and Windows 10 and everything worked perfectly, so I don't think the problem is caused by the browser or client system.

**Comment by szewczyk-it** [comment]
Ad. 1) It is mp4 file. Link to sample file: https://owncloud.szewczyk.it/index.php/s/vC7de8YiNH4CGwk
Ad. 2) 
> ownCloud is installed on CentOS 6.5 from yum repository: http://download.opensuse.org/repositories/isv:ownCloud:community/CentOS_CentOS-6/isv:ownCloud:community.repo
> apache webserver
> is it possible I have bad php config? But in Edge is OK (but just after full loaded file though player must read file sequently?)

**Comment by Instagit** [comment]
I tested the video on two OwnCloud installations on Ubuntu and it works on both. Maybe it's a problem with the streaming. Could you open the Firefox developer tools and check the status code when you open the video? It should be "206 Partial Content".

For me it works even without xsendfile, but could you try to install the module and see if that makes a difference?

https://doc.owncloud.org/server/7.0/admin_manual/configuration/serving_static_files_configuration.html

**Comment by szewczyk-it** [comment]
You have right.
Sorry for this issue, but in any tutorial I does't read about xsendfile. Thank you for help - your suggestion resolved my problem.

**Comment by jancborchardt** [comment]
@Instagit we’re thinking about replacing the default files_videoviewer of ownCloud with your app – if you like. :)

However seek doesn’t work in a lot of cases where it works with the current video viewer. Tested with some mp4 and ogv files and both have that issue. Is it possible to fix that?

**Comment by jancborchardt** [comment]
cc @LukasReschke for this as well. We apparently threw out xsendfile with ownCloud 8.2, so we ideally need to find a way that this works without that.

**Comment by Instagit** [comment]
@jancborchardt , I'd be glad to have this player as the default video player in ownCloud. I'm going to try to fix what I can.

For testing H264 MP4 files, I use these videos: http://www.sample-videos.com/. All the MP4 videos encoded with *h264 Main profile* work for me in Firefox, including seeking, with ownCloud 8.2.0, but they don't work in Chrome. Can you confirm this?
The 640x360 versions are encoded with a different profile and don't work in either browser, but I think that's correct behaviour.

**Comment by jancborchardt** [comment]
Yeah, I do have this problem in Chrome only. Firefox works fine with the videos I tested.
